# Setup
title:               eff3ct's st0rage
tagline:             'Dev Blog'
description:         'Dev & PS'
url:                 http://eff3ct.github.io/
baseurl:             '/eff3ct'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              eff3ct
  url:               https://github.com/eff3ct
  email:             effect2110@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
