# Setup
title:               eff3ct's st0rage
tagline:             'Dev Blog'
description:         'Dev & PS'
url:                 https://eff3ct.github.io
baseurl:             ""
paginate:            5
permalink:           pretty
futrue:              true

# About/contact
author:
  name:              eff3ct
  url:               https://github.com/eff3ct
  email:             effect2110@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
